### ISSUE TITLE
Bump Ruby to 2.5.4

### ISSUE THREAD

**Issue by cveneziani** [lewagon/setup#103]
Last March, Ruby 2.5.4 has been released.

It includes bug fixes but also a **security update** of the bundled RubyGems.
Source: https://www.ruby-lang.org/en/news/2019/03/13/ruby-2-5-4-released/

Could we consider upgrading the setup to this safer version?

*On a side note, can we also consider bumping directly to Ruby 2.6 which has been released 6 months ago?*

**Comment by ssaunier** [comment]
Hi @progapandist, the main reason who prevented us to follow the [latest stable version](https://www.ruby-lang.org/en/downloads) of Ruby for the students was Kitt hosted on Elastic Beanstalk, with a cumbersome way of upgrading the Ruby version. Now that Glovebox is there, it's just a matter of upgrading the Ruby version in that microservice only, leaving Kitt agnostic to the Ruby version used by students.

Could you take care of updating both the Setup Guide + Glovebox to use the **2.6.3** version?

Thanks!
