### ISSUE TITLE
Should WSL have it's own link in the readme?

### ISSUE THREAD

**Issue by The-Pavel** [lewagon/setup#111]
It seems there is no direct link to WSL setup guide from the setup repo readme, or the Windows setup readme.

Last batch this lead to some students not knowing that WSL is an option during setup day.

**Suggested fix:** On the repo readme, include an image that links to the WSL setup, next to MacOS, Ubuntu and Windows images.

**Comment by barangerbenjamin** [comment]
This issue can be closed following new WSL2 setup
