### ISSUE TITLE
Wagon Setup for Ubuntu shell in Windows 10

### ISSUE THREAD

**Issue by bernardlemoullec** [lewagon/setup#114]
Hello,

Is it possible to setup your PC for Le Wagon directly from the Ubuntu shell in Windows 10 (instead of having to create a Linux partition)? 
https://www.microsoft.com/en-us/p/ubuntu/9nblggh4msv6?activetab=pivot:overviewtab
If so, how should students do it?

Thanks and regards,
B

**Comment by db0sch** [comment]
hello @bernardlemoullec 

You can have a look at this setup guide.
https://github.com/lewagon/setup/blob/master/WINDOWS_LINUX_SUBSYSTEM.md

Best
