### ISSUE TITLE
Check if virtualization is already enabled

### ISSUE THREAD

**Issue by db0sch** [lewagon/setup#136]
It seems we can check from Windows if virtualization is already enabled, before diving into the BIOS / UEFI settings.

Running these steps:

```
1. Press Ctrl + Alt + Del.
2. Select Task Manager.
3. Click the Performance tab.
4. Click CPU.
5. The status will be listed under the graph and will say "Virtualization: Enabled" if this feature is enabled.
```

And you end up with this window:
![image](https://user-images.githubusercontent.com/6984619/78345748-589a2100-759e-11ea-9aa1-99467b48fb8c.png)

@barangerbenjamin what do you think?
If so we need to re-do the screenshot to remove the credit in the lower right.

**Comment by barangerbenjamin** [comment]
That will work, will add it to the setup ASAP 👍

**Comment by db0sch** [comment]
thanks 🙏
