### ISSUE TITLE
PyV8 error message while launching SublimeText

### ISSUE THREAD

**Issue by yannklein** [lewagon/setup#138]
During the Setup day, after running the dotfiles programs and opening SublimeText via `stt`, the following SublimeText error popup message appears:
```
Error while loading PyV8 binary: ext code 1
Try to manually install PyV8 from
https://github.com/emmetio/pyv8-binaries
```
It looks like it's related a the Emmet package [installation issue](https://github.com/sergeche/emmet-sublime/issues/417), maybe because we use our coworking space wifi (in Tokyo)?
I believe we're not the only ones to have this issue(?). If it is the case, shall update our dotfile/SublimeText install to avoid it?

Note: except the message popup, the problem doesn't induce any issue for our students. So, definitely not a critical problem.

**Comment by barangerbenjamin** [comment]
Hello @yannklein, sorry for the delay and thank you for reporting 🙏 

This is this rarely an issue so I'd rather not add it to an already lengthy setup ;)

Otherwise to fix it: 
```
cd ~
SUBLIME_FOLDER="Library/Application Support/Sublime Text 3/Installed Packages"
curl -L https://github.com/emmetio/pyv8-binaries/raw/master/pyv8-osx-p3.zip > v8.zip
mkdir -p $SUBLIME_FOLDER/PyV8

cd $SUBLIME_FOLDER/PyV8
unzip $HOME/v8.zip
```

Will close this issue. Hoping you wont have the issue again. 👍
