### ISSUE TITLE
wsl --set-version vs --upgrade

### ISSUE THREAD

**Issue by mdik** [lewagon/setup#143]
Hi,

I encountered several setups with students where `wsl -l -v` as well as `wsl --set-version Ubuntu 2` produced only `wsl`'s usage output, and `wsl --upgrade Ubuntu` was the command that was working.

I could not figure out what the differences in Windows setups were (maybe Home vs Pro?), but until we figure out, we should give both commands in a "if `wsl --set-version Ubuntu 2` does not work, try `wsl --upgrade Ubuntu`" way, in my opinion.

Sincerely,

Malte

**Comment by barangerbenjamin** [comment]
Hey @mdik, thank you for reporting 👌

What is the error some students encounter?

The flag --upgrade does not exist in the list of available command to wsl when I run `wsl --help` 
Could you indicate to me where you found the info so I can run some tests?

The `/upgrade` flag does exist but is used to switch the type of filesystem from the old one to the new one for WSL, see the answer of (Sven Groot - Senior engineer working on WSL) https://github.com/MicrosoftDocs/WSL/issues/280

It shouldn't impact the conversion to WSL 2.

**Comment by mdik** [comment]
they don't get an error, they get the *usage* page, something like you'd get with most commands if you add `-h`. This is how I learned about `--upgrade` in their installations, when they shared their screens.

I have no idea where the difference in WSL installations comes from.

I'd guess either Windows edition (Pro vs Home), or silent mis-success in installing Insider or WSL 2.

Either way, those seem to not matter too much, as the installations go on without problems from there on.

**Comment by barangerbenjamin** [comment]
Closing this issue as it's getting nowhere.
If some conversion fail it will be investigated.
Also, wsl2 coming in stable version outside insider program May 28 🤞
