### ISSUE TITLE
WSL vs "intro"

### ISSUE THREAD

**Issue by mdik** [lewagon/setup#145]
As the WSL guide is compiled, `_partials/intro.md` is hardly an intro any more, and can be a bit confusing. Maybe we could just leave it out?

(Also phrasings like "Grab a text editor" that read like "Do this now" are not helpful.)

**Comment by barangerbenjamin** [comment]
Hey @mdik and thank you for reporting 🙏 
I agree that the intro shouldn't be where it is in the `Windows.md`
I've removed it to put the information at the top to stay coherent with the other setups 👌
