### ISSUE TITLE
WSL v2 Emmet on VSCode

### ISSUE THREAD

**Issue by andrerferrer** [lewagon/setup#148]
Today, a student using VSCode had some issues with emmet and the .erb extension.
All that need to be done is to config the settings.json of emmet (it comes by default with vscode).
go to `File > Preferences > Settings` then look for "emmet", clic on `edit in settings.json` and add:
```
"emmet.includeLanguages": {
        "erb": "html"
    },
```

I'm not sure how to present it in the `WINDOWS.md` file though

**Comment by barangerbenjamin** [comment]
Thanks for reporting @andrerferrer 🙏 
Just added it, also added the expansion on the `Tab` key to have the same behavior as Sublime 👌
