### ISSUE TITLE
PostgreSQL credentials

### ISSUE THREAD

**Issue by jramiresbrito** [lewagon/setup#172]
What are the credentials to access the database we create in setup?

PS: I'm on windows using WSL2.

I've tried `CREATE USER yourname WITH SUPERUSER PASSWORD 'yourpassword';`

but when I try to connect using pgadmin4 it refuses to connect:

![postgres_error](https://user-images.githubusercontent.com/47673606/83954768-7c8a1500-a822-11ea-8656-9fd3f6fb92dd.png)

**Comment by barangerbenjamin** [comment]
Hi @jramiresbrito 

Here it looks like your PostgreSQL server is not running.
Is your WSL terminal open?
The password should be your WSL session's one.

This is not a setup issue so I will close it. You should reach out to the #help on Slack to follow up on this one 👍

**Comment by jramiresbrito** [comment]
It is running, yes the wsl2 is up.
