### ISSUE TITLE
Windows Insider Program

### ISSUE THREAD

**Issue by carlosmendes** [lewagon/setup#180]
windows insider program is still needed in some PCs (hp pavilion x360 convertible).

We have a student that still does not have available the 2004 windows update so she needed to register into the windows insider program

**Comment by Disco-Chef** [comment]
Does using Windows Update Assistant help after downloading the May Update (2004) perhaps help?
https://www.microsoft.com/en-us/software-download/windows10
Once you click on Update Now, and run the downloaded file, the Windows Update Assistant comes up and downloads the updates, after which a reboot is required and you should be on version 2004.

**Comment by carlosmendes** [comment]
thank you, now we already proceed with the Windows insider program and the student PC is up and running. Probably it would work as you suggest to manually download the update, since in the windows update page of the computer itself there was an warning saying that the PC was still not ready to do it automatically.
