### ISSUE TITLE
Stubborn laptops refusing to update beyond windows 10 version 1909

### ISSUE THREAD

**Issue by Disco-Chef** [lewagon/setup#181]
In setting up multiple machines over the last couple of weeks, some of the laptops do not find any new updates beyond 1909. Specifically, checking for updates using windows' "Check for Updates" simply returns that you are up to date.

In these cases, this can be worked around by going to https://www.microsoft.com/en-us/software-download/windows10 and downloading the recent updates from there.

After clicking update now, there is a compatibility check on the hardware:
![image](https://user-images.githubusercontent.com/49205098/85295494-4eead000-b4a0-11ea-95c7-49d3d4d2c4a5.png)
Not exactly sure what to look out for but in my experience, the 4 machines I updated to the May update version all passed this check.

Then, the option to upgrade is presented:
![image](https://user-images.githubusercontent.com/49205098/85295611-7772ca00-b4a0-11ea-9f75-db25c9d28904.png)

This in turn brings up the Windows 10 Update Assistant which proceeds to download the update:
![image](https://user-images.githubusercontent.com/49205098/85294985-96249100-b49f-11ea-9bfd-3ffe32d28606.png)
which should be noted can take a while to download.

Once the download is finished, the window now has a 30 minute countdown and a prompt asking the user to restart manually, otherwise it will do so automatically when the countdown ends:
![image](https://user-images.githubusercontent.com/49205098/85297030-85294f00-b4a2-11ea-8c47-3d9923b886dd.png)

After the update, the version is at least 2004 and the rest of the setup can be followed 🚀

**Comment by barangerbenjamin** [comment]
Hi @Disco-Chef 
Thank you for reporting 🙏 

This issue is due to Microsoft slowly rolling out this major update, I thought that would be done almost 1 month after release! Hopefully, it will be the case soon.

I will add your guidelines to the WSL cheatsheet in the meantime as this problem is only temporary.
https://github.com/lewagon/setup/blob/master/wsl_cheatsheet.md
Thank you 👍

**Comment by Disco-Chef** [comment]
No worries, always a pleasure! 🙇
