### ISSUE TITLE
No way for students to change Windows Terminal Preview settings at the current suggested point of doing so

### ISSUE THREAD

**Issue by Disco-Chef** [lewagon/setup#183]
Minor issue for most people, then I thought about this from a student's perspective:

There is no way (that the students instinctively know, that is) to edit the .json file for the settings when making the changes to Windows Terminal Preview settings. All they will see is this

![image](https://user-images.githubusercontent.com/49205098/85308711-d2f98380-b4b1-11ea-9909-650a952cd7f3.png)

OR this

![image](https://user-images.githubusercontent.com/49205098/85308755-e4db2680-b4b1-11ea-80bc-5c625b98dcbc.png)
(from which Notepad can be used)

A few possible workarounds:
-use Notepad for only these changes just this once, with the "Always use this program to open .json files?" unticked.
            OR
-Installing VSCode before this step
            OR
-Recommending the changes in settings for default terminal and opening path be done after they have installed a text editor, but then each time they open this Terminal after closing it, they should be reminded to paste the commands in an ubuntu tab

**Comment by barangerbenjamin** [comment]
Fixed with #187 👍
