### ISSUE TITLE
"This update only applies to machines with the Windows Subsystem for Linux" fix to add in the setup page or wsl_cheatsheet

### ISSUE THREAD

**Issue by Disco-Chef** [lewagon/setup#189]
Can we add this to the windows setup page or wsl_cheatsheet:
 
Right click and select uninstall on the wsl2 update file if you get this error: "This update only applies to machines with the Windows Subsystem for Linux", then run the file again and voilà.

**Comment by barangerbenjamin** [comment]
Hey @Disco-Chef 
As per usual, big thank you for reporting 🙌 
I've updated the instructions.
