### ISSUE TITLE
Issues with setup

### ISSUE THREAD

**Issue by gfortaine** [lewagon/setup#19]
Hello,

I am currently facing 2 issues with this setup (my computer uses Ubuntu 16.04 LTS) :

1) I need to add the following command to login into GitHub (otherwise I have an error "Permission denied (publickey).") :

$ ssh-add ~/.ssh/id_rsa 

2) The following command doesn't seem to work :

$ psql --command "CREATE ROLE `whoami` LOGIN createdb;"

I have the following error : "ERROR: role "postgres" already exists". However, replacing  `whoami` with my usual login seems to work.

**Comment by tgautier** [comment]
Yeah I also had this problem on another student computer with Ubuntu.

Generally, the `postgres` role is created by the aptitude install procedure and the `psql` cli is configured to use the `postgres` role by default and not the username.

This is why, I think, the `whoami` command, in the psql context, outputs `postgres` and not the username.

**Comment by Maxeeeeeeeeem** [comment]
same as gfortaine I had to use command
`ssh-add .ssh/id_rsa` 
to be able to add an identity to the agent
