### ISSUE TITLE
Sure-fire way to get into the BIOS

### ISSUE THREAD

**Issue by Disco-Chef** [lewagon/setup#191]
Seeing as some machines are older, or that some brands decide to use different keys when booting to go to the BIOS (or sometimes simply do not display information on boot as to which non-standard button it is) we could also add this "fool-proof" way to get into the BIOS, through "Recovery Options":

![image](https://user-images.githubusercontent.com/49205098/90247822-b5082980-de37-11ea-9d49-fc822fe5820b.png)

and then selecting "Restart now" under "Advanced start-up":

![image](https://user-images.githubusercontent.com/49205098/90247872-ca7d5380-de37-11ea-99c5-5e247caef561.png)

This will restart the machine and boot into a new menu, in which selecting "Troubleshoot" -> "Advanced Options" -> "UEFI Firmware Settings" -> "Restart" will boot into the BIOS where the necessary changes can be made (particularly interesting for students who want to install ubuntu as a dual boot or standalone).

Granted, it is a bit longer and convoluted, but it is a "sure-fire" way that works all the time with Windows 10

**Comment by barangerbenjamin** [comment]
Thank you @Disco-Chef 
On it 😎
