### ISSUE TITLE
Reload Required Button Missing

### ISSUE THREAD

**Issue by lucien-george** [lewagon/setup#201]
For windows setup one step asks the students to click on `reload required` which doesn't exist. Might need to replace that by `quit and restart vs code`

![image](https://user-images.githubusercontent.com/9754165/95658459-7bd7f700-0b12-11eb-819a-39e4cd28832b.png)

**Comment by v-natalia** [comment]
+1 just doing the setup in Barcelona, and we had the same "issue"
