### ISSUE TITLE
Add NVM to the setup

### ISSUE THREAD

**Issue by juliends** [lewagon/setup#214]
We need to add **nvm** to our setup in order to control the version of node installed by our students.
This will prevent errors like we had today on Rails D1 where [webpacker](https://github.com/rails/webpacker) does not support the last version of node.

Todo:
- [ ] Find the correct version of node we want to support 
- [ ] Add it to every setup

**Comment by db0sch** [comment]
Today, we made it work with `nvm install 12.16.2`

**Comment by db0sch** [comment]
but maybe the latest LTS (14.something) would be just fine. Needs testing
