### ISSUE TITLE
Blog Le Wagon | Duplicate blog

### ISSUE THREAD

**Issue by a-ferre** [lewagon/setup#219]
Hi Sébastien, it is a pleasure to e-meet you!

My name is Albert and I will be joining Le Wagon Tokyo bootcamp on the January 2021 batch.
I was doing my prep work watching your "Technical Workflow for a Startup" workshop video (kudos for that!) and at the same time reading some blogs you have in your website.
I found there is a duplicate blog from Clémentine Delisse, kindly find the video below for your reference:

https://recordit.co/KcQWAQ6RVW

Stay safe et à bientôt!

Albert

**Comment by barangerbenjamin** [comment]
Hi @a-ferre 

Thank you for reporting the issue, we will fix that asap.
Many thanks for contributing and best of luck with the course 👍
