### ISSUE TITLE
WSL setup: disable copy-paste warning in Windows terminal

### ISSUE THREAD

**Issue by dmilon** [lewagon/setup#245]
When students copy-paste commands from the setup instructions, they see this kind of warning every time:

https://user-images.githubusercontent.com/6956305/88414668-15a0cb00-cd92-11ea-936c-b71e6c459343.png

A quick research showed me that this behavior could be turned off: https://github.com/microsoft/terminal/issues/7482

Is it something we could/should add the WSL setup @barangerbenjamin ? 

I guess the question is relevant for https://github.com/lewagon/data-setup too.

**Comment by barangerbenjamin** [comment]
Works like a charm, will add it 💪
