### ISSUE TITLE
Outdated gif that generates confusion

### ISSUE THREAD

**Issue by Elmolesto** [lewagon/setup#247]
[This gif](https://raw.githubusercontent.com/lewagon/setup/master/images/wsl_ubuntu_file_system.gif) is confusing because it shows how to add the /code folder as a quick link but the students doesn't have it at that time in the setup.

**Comment by Eschults** [comment]
Related 👉 https://lewagon-alumni.slack.com/archives/G02NFDT0J/p1611064096071800 👌
