### ISSUE TITLE
M1 Macbook students - using terminal with rosetta enabled

### ISSUE THREAD

**Issue by SebiBasti** [lewagon/setup#248]
Maybe we can use [this](https://lewagon-alumni.slack.com/archives/G02NFDT0J/p1610394683060100) to update the setup for M1 Macbook students. We had tons of problems with those new machines today and this step-by-step manual helped.

**Comment by barangerbenjamin** [comment]
Hi @SebiBasti,

We have a cheat sheet about M1 chips here: https://github.com/lewagon/setup/blob/master/apple_m1_cheatsheet.md
Could you there what you find relevant? 🙏

**Comment by SebiBasti** [comment]
Sure, I will do that. 👍

**Comment by gmanchon** [comment]
@SebiBasti the new version of the setup uses Terminal under Rosetta following the instructions from Andy and should solve these https://github.com/lewagon/setup/pull/263
