### ISSUE TITLE
Issue with check-up and possible solution

### ISSUE THREAD

**Issue by v-natalia** [lewagon/setup#253]
The problem: https://lewagon-alumni.slack.com/archives/G02NFDT0J/p1611079907082300.
Students doing the setup get an alert that they don't have a picture in Github even when the picture is there and its size is more than 1024x1024. (happened for windows and ubuntu machines)
The file in https://raw.githubusercontent.com/lewagon/setup/master/check.rb has a problem on line 66.
**It says:**     
```
content_length = `curl -s -I #{avatar_url} | grep 'Content-Length:'`.strip.gsub("Content-Length: ", "").to_i

```
**it should be:** 
```
content_length = `curl -s -I #{avatar_url} | grep 'content-length:'`.strip.gsub("content-length: ", "").to_i

```
I check it and it worked for my profile in ubuntu. 
I hope it helps !

**Comment by jsphwllng** [comment]
https://github.com/lewagon/setup/pull/254
PR here.
