### ISSUE TITLE
The check of the BROWSER variable for WSL currently always fails

### ISSUE THREAD

**Issue by Disco-Chef** [lewagon/setup#259]
When setting the variable at this step:

https://github.com/lewagon/setup/blob/master/WINDOWS.md#linking-your-default-browser-to-ubuntu

```[ -z "$BROWSER" ] && echo "ERROR: please define a BROWSER environment variable ⚠️" || echo "Browser defined 👌"```
The check command above will always return "ERROR: please define a BROWSER environment variable ⚠️" because the instance of the terminal they have open won't be aware of the changes made to ```~/.zshrc```

I will gladly make the PR for it, but I was wondering which way forward would be deemed best:

-Asking the students to restart their terminal before running the check command
OR
-Add ```source ~/.zshrc;``` at the beginning of the check command to instead be:
 ``````source ~/.zshrc;[ -z "$BROWSER" ] && echo "ERROR: please define a BROWSER environment variable ⚠️" || echo "Browser defined 👌"``````  (even as two separate commands, but at least put to them together)
OR
-Add a notice to either run the source command or restart their terminal at each of the options for browser selection (firefox, chrome, edge). That could potentially be less confusing to the unfamiliar and/or look better than the abovementioned other options, presentationally speaking, but it is slightly bugging me that it wouldn't be very DRY 😅 

🖖

**Comment by gmanchon** [comment]
Hello @Disco-Chef, followed the first option which is pretty simple, and the students need to restart their terminals anyways 👍 Thanks for the heads up ! https://github.com/lewagon/setup/pull/265
