### ISSUE TITLE
Installing NVM

### ISSUE THREAD

**Issue by gkeidel** [lewagon/setup#261]
- After the command:
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.37.2/install.sh | bash

- Run this 2 commands, otherwise the nvm -v it will fail 
export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm

**Comment by barangerbenjamin** [comment]
Hi @gkeidel 👋 

We have those 2 lines in our [dotfiles](https://github.com/lewagon/dotfiles/blob/d9ffcd698ac9ee7b86dac24e0b6014619ac43d84/zshrc#L26) that the student fork during setup.

**Comment by gkeidel** [comment]
Hello @barangerbenjamin!
I did the complete setup and, really, I didn't see these two lines. I'm sorry for the failure!
And thanks for the reply!
