### ISSUE TITLE
Permissions Issue with Zsh

### ISSUE THREAD

**Issue by Willgg** [lewagon/setup#270]
Issue with Zsh setup (with MacBookAir M1):

Here is the error message displayed after installing Zsh : 
```
[oh-my-zsh] Insecure completion-dependent directories detected:
drwxrwxr-x  3 willgodard  admin   96 12 mar 16:17 /usr/local/share/zsh
drwxrwxr-x  6 willgodard  admin  192 12 mar 16:21 /usr/local/share/zsh/site-functions

[oh-my-zsh] For safety, we will not load completions from these directories until
[oh-my-zsh] you fix their permissions and ownership and restart zsh.
[oh-my-zsh] See the above list for directories with group or other writability.

[oh-my-zsh] To fix your permissions you can do so by disabling
[oh-my-zsh] the write permission of "group" and "others" and making sure that the
[oh-my-zsh] owner of these directories is either root or your current user.
[oh-my-zsh] The following command may help:
[oh-my-zsh]     compaudit | xargs chmod g-w,o-w

[oh-my-zsh] If the above didn't help or you want to skip the verification of
[oh-my-zsh] insecure directories you can set the variable ZSH_DISABLE_COMPFIX to
[oh-my-zsh] "true" before oh-my-zsh is sourced in your zshrc file.
```

Solution is : 

- Open Sublime text app then go to File > Open
- Browse to /Users/your_name et press cmd + shift + "." to display hidden files and open .zshrc
- Past the line `ZSH_DISABLE_COMPFIX=true` **before** the line `source $ZSH/oh-my-zsh.sh`
- Save the file and restart your terminal: cmd + "Q"

Original solution found here : https://github.com/robbyrussell/oh-my-zsh/issues/6835#issuecomment-390216875

**Comment by barangerbenjamin** [comment]
Hi @Willgg 

Thank you for reporting 👌 
This being an issue only for M1 machines. I've added the fix to the [cheatsheet](https://github.com/lewagon/setup/blob/master/apple_m1_cheatsheet.md) to not pollute the setup :) 

Thank you 🚀
