### ISSUE TITLE
Github CLI login command unclear for some students

### ISSUE THREAD

**Issue by Elmolesto** [lewagon/setup#290]
I've seen a lot of students replacing his user and email here:`gh auth login -s 'user:email' -w`.
It's clear to me, but to make it clearer, you could put a warning not to complete your username and email there.

**Comment by ssaunier** [comment]
Thanks @Elmolesto for reporting, I rephrased the previous paragraph, hope it's clearer for them now.

**Comment by Elmolesto** [comment]
Thanks @ssaunier!
