### ISSUE TITLE
check.rb script URL returns a 404

### ISSUE THREAD

**Issue by Disco-Chef** [lewagon/setup#297]
In the final check script:
`curl -Ls https://raw.githubusercontent.com/lewagon/master/vscode/check.rb > _.rb && ruby _.rb && rm _.rb || rm _.rb`

The url returns a 404
https://raw.githubusercontent.com/lewagon/master/vscode/check.rb

**Comment by Eschults** [comment]
Thank you @Disco-Chef for reporting 🙏
