### ISSUE TITLE
Add note to "Disable SSH passphrase prompt" to open .zshrc

### ISSUE THREAD

**Issue by lislis** [lewagon/setup#304]
Students were confused where to find the 
```plugins=(gitfast last-working-dir common-aliases zsh-syntax-highlighting history-substring-search ssh-agent)```
line.
I'd suggest adding something like "Open your .zshrc in VSCode with `code ~/.zshrc`" or something like that

**Comment by dmilon** [comment]
HI @lislis :wave: Thank you for reporting this issue. The instructions have been updated to make it clearer for students: 

![image](https://user-images.githubusercontent.com/37899667/135801264-48db88ba-6f18-4b05-9266-4560ea5dfe73.png)
