### ISSUE TITLE
Trust fullstack-challenges and data-challenges folder with VSCode

### ISSUE THREAD

**Issue by db0sch** [lewagon/setup#310]
Add a section to ask students doing the setup to open their main challenges folder (for web or data) to "trust" it in VSCode

**Comment by dmilon** [comment]
Unfortunately, when students reach the end of the setup, they don't have the `fullstack-challenges` cloned on their computer yet. The clone step happens when they first log into Kitt, when the setup is done. 

This issue was not reported by teachers or batch managers. I'm closing.
