### ISSUE TITLE
ruby not set to the default on MacOS on M1 after the rbenv install and version set

### ISSUE THREAD

**Issue by jp-nullpod** [lewagon/setup#313]
ruby -v still gives the default version that comes with MacOS M1 i.e 2.6.x

In the `~/.zshrc` file, I have added:

`
export PATH="$HOME/.rbenv/bin:$PATH"
`
`
eval "$(rbenv init -)"
`

 and after a terminal restart, it fixed the issue. The ruby -v set by rbenv is correctly used on the prompt.

**Comment by Eschults** [comment]
Hello @jp-nullpod 👋 

Thank you for reporting 🙏 those lines are [already part of students `.zshrc`](https://github.com/lewagon/dotfiles/blob/38190cc35ba527eb475ef303f54c19481ae63616/zshrc#L20-L21) -- would you mind removing the lines you added, then restarting the terminal and check if the `ruby -v` output is correct ❔ 
Thank you 🙏
