### ISSUE TITLE
Unscaped username creating a role for PSQL

### ISSUE THREAD

**Issue by Elmolesto** [lewagon/setup#317]
We're on rails week and I've realized that a student doesn't have the role in postgres.
The thing is that the student username contains a dash, so to fix the problem, we ran the command this way (scaping the `whoami` result)
```sudo -u postgres psql --command 'CREATE ROLE "`whoami`" LOGIN createdb;'```

Reference:
https://github.com/lewagon/setup/blob/master/ubuntu.md#postgresql

**Comment by dmilon** [comment]
Hi @Elmolesto :wave: 

Thank you for your report :pray: 

I can see that this command is now included in the [Windows](https://github.com/lewagon/setup/blob/master/windows.md#postgresql) and [Ubuntu](https://github.com/lewagon/setup/blob/master/ubuntu.md#postgresql) setup instructions but not in [macOS](https://github.com/lewagon/setup/blob/master/macos.md#postgresql)

Do you remember if you encountered this issue on a Mac? :pray:

**Comment by Disco-Chef** [comment]
This is what is in the windows and ubuntu setup right now:
```
sudo -u postgres psql --command "CREATE ROLE `whoami` LOGIN createdb;"
```

which is not what was suggested:
```
sudo -u postgres psql --command 'CREATE ROLE "`whoami`" LOGIN createdb;'
```
so we still need to update those setups, unless there's more shell quote rules i'm forgetting (which is honestly very likely).

Had a student today who had this issue.
