### ISSUE TITLE
Confusion over which terminal to run the command to check connection to Ubuntu (windows)

### ISSUE THREAD

**Issue by Disco-Chef** [lewagon/setup#346]
50/50 they run it in cmd or powershell instead. Suggest we explicitly say: "The Ubuntu terminal"

**Comment by dmilon** [comment]
Hi @Disco-Chef :wave: 

Are you talking about [this section](https://github.com/lewagon/setup/blob/master/windows.md#connecting-vs-code-to-ubuntu)?

**Comment by Disco-Chef** [comment]
Aye aye

**Comment by andrerferrer** [comment]
Supporting this @dmilon

**Comment by dmilon** [comment]
I've just fixed it by https://github.com/lewagon/setup/commit/a263193c44f3515cdf934c94ab074b915a214dee

See https://github.com/lewagon/setup/blob/master/windows.md#connecting-vs-code-to-ubuntu
