### ISSUE TITLE
WSL - Change how to access Starting Directory 

### ISSUE THREAD

**Issue by andrerferrer** [lewagon/setup#349]
So, I had today more than a dozen students having issues with the starting directory.

Therefore, I recommend replacing [this](https://github.com/lewagon/setup/blob/master/_partials/windows_terminal.md):
![image](https://user-images.githubusercontent.com/45776359/148564143-0468c3fb-2b98-4f47-9300-caf496858d95.png)

with:
```
"commandline": "wsl.exe ~",
```

It works just as fine on my Win 10
![image](https://user-images.githubusercontent.com/45776359/148564245-a4c1cc15-4257-44ef-bee3-4df08154e9b1.png)

Idk about Win 11, though.

Credits go to @v-natalia.

These are my 2 cents. Ty for the attention 🤓

**Comment by v-natalia** [comment]
Saw this maaaaany time this week. The error is described here https://github.com/v-natalia/setup-fixes/blob/master/fixes.md#error-after-trying-to-do-rbenv-install-for-ruby-install-binreadlink-no-such-file-or-directory same happens for data students when installing pyenv. PATH is ok. Don't hesitate to ping me for more insights

**Comment by dmilon** [comment]
I tried it on my hand and it's working :ok: This is way easier! I've implemented the change https://github.com/lewagon/setup/commit/55dbb007c2db467f5a441e5e94386b7035d37274 Thank you @andrerferrer and @v-natalia :pray:
