### ISSUE TITLE
Changes to rails system tests guidelines. Update sudo command

### ISSUE THREAD

**Issue by Disco-Chef** [lewagon/setup#354]
With the current install instructions of rails Stupid Coaching, I had some windows students getting:
`E: Unable to locate package google-chrome-stable_current_amd64.deb`

Then it hit me:  command should be `sudo apt install ./google-chrome-stable_current_amd64.deb` if using `apt` with a path to a deb file and not fetching by package name from the Ubuntu repositories.

All three had to also then `sudo apt --fix-broken install` for some reason 🤷‍♂️

**Comment by dmilon** [comment]
FYI, I'm adding an extra command line to remove the `.deb` file after installation.
