### ISSUE TITLE
Set the default version of Ruby can fail on MacOS > Catalina

### ISSUE THREAD

**Issue by M0nkeySan** [lewagon/setup#357]
According to the [tutorial ](https://github.com/lewagon/setup/blob/master/macos.md#ruby)the command `rbenv global 3.0.3` should setup the default version of ruby.
But since MacOS Catalina, a version of ruby is embedded with the OS and can't be uninstalled.

Solution : 

You must add `eval "$(rbenv init -)"` to your `~/.zshrc`
cf : https://stackoverflow.com/a/58804915

**Comment by dmilon** [comment]
Hi @M0nkeySan :wave: Thank you for your feedback :pray: 

This line is already present in [the zshrc file](https://github.com/lewagon/dotfiles/blob/master/zshrc#L21) you can get by [forking and cloning the dotfiles](https://github.com/lewagon/setup/blob/master/macos.md#dotfiles-standard-configuration).
