### ISSUE TITLE
Suggestion: FIX: Cannot apt-get update / apt update

### ISSUE THREAD

**Issue by barrrricade** [lewagon/setup#358]
Took me a while to figure this out.
If cannot `sudo apt update` or `sudo apt-get update`

you can add a known DNS server to your system
`echo "nameserver 8.8.8.8" | sudo tee /etc/resolv.conf > /dev/null`
then `sudo apt update` or `sudo apt-get update`

[Reference](https://askubuntu.com/questions/91543/apt-get-update-fails-to-fetch-files-temporary-failure-resolving-error)

My current system:
Windows 10
WSL V2

**Comment by dmilon** [comment]
Hi @barrrricade :wave: Thank you for your feedback :pray: 

Your solution seems similar to [the one in the Windows cheatsheet](https://github.com/lewagon/setup/blob/master/docs/windows_cheatsheet.md#add-a-custom-dns-server-address-to-wsl). 

You tried it and it didn't work?

**Comment by barrrricade** [comment]
@dmilon 
Oh dang. I didn't see this.
The link wasn't obvious in the setup.

👍
