### ISSUE TITLE
With macOS Sierra, some modify is needed for the passphrase of secret key

### ISSUE THREAD

**Issue by hidehiro98** [lewagon/setup#36]
With macOS Sierra, without below modification in `.ssh/config`, we have to everytime type the passphrase of secret key.

```
Host *
   AddKeysToAgent yes
   UseKeychain yes
```

https://apple.stackexchange.com/questions/254468/macos-sierra-doesn-t-seem-to-remember-ssh-keys-between-reboots

**Comment by alex-felix** [comment]
@hidehiro98 you can type `ssh-add` in terminal and it won't ask you again until you reboot

**Comment by hidehiro98** [comment]
yes, but it is annoying that typing `ssh-add` every time.

**Comment by ssaunier** [comment]
@hidehiro98 Thanks for reporting, I updated the [OSX](https://github.com/lewagon/setup/blob/master/OSX.md) readme with this.
