### ISSUE TITLE
Ubuntu setup: curl used before it is installed (Issue of order)

### ISSUE THREAD

**Issue by Disco-Chef** [lewagon/setup#366]
Hello team :wave: 

I was setting up an Ubuntu machine today and noticed that `curl` does not come with a default install of Ubuntu 20.04 :cry: 

In the Ubuntu readme, we are asking the students to use `curl` for the Github CLI Installation section (which won't work) and we ask them to install `curl` on the next step :upside_down_face: 

![image](https://user-images.githubusercontent.com/49205098/160139921-8568477a-6cb5-4e25-86ef-fc1a238116e8.png)

Recommend we change the order of those two (or if we can use `wget` for the first command in that section we can do that instead maybe?)

:bow: :vulcan_salute:

**Comment by v-natalia** [comment]
Hey I saw the same with a WSL2 user, could we move the step of installation of curl before the GitHub CLI installation also in that partial, please?
