### ISSUE TITLE
Proofread cli_tools & gh_cli partials Spanish translation

### ISSUE THREAD

**Issue by dmilon** [lewagon/setup#370]
In https://github.com/lewagon/setup/pull/369 we are making changes in [some of our partials](https://github.com/lewagon/setup/pull/369/files#diff-8ce4c4af01166c2b6458748fdec5aa50a217aec720d14f28e0f3f002c095ab97): 
- the `ssh_key` partial is removed and its content is updated and merged into the `gh_cli` partial
- the `git` and `zsh` partials are merged into one single `cli_tools` partial

Since most of the new partials content is coming from existing content, I've copy-pasted and adapted the Spanish partials. 

Let's just proofread them and implement any required changes: 
- [ ] Check that [the Spanish cli_tools partial](https://github.com/lewagon/setup/blob/22q4-setup-bug-bash/_partials/es/cli_tools.md) is the correct translation of [the English cli_tools partial](https://github.com/lewagon/setup/blob/22q4-setup-bug-bash/_partials/cli_tools.md)
- [ ] Check that [the Spanish gh_cli partial](https://github.com/lewagon/setup/blob/22q4-setup-bug-bash/_partials/es/gh_cli.md) is the correct translation of [the English gh_cli partial](https://github.com/lewagon/setup/blob/22q4-setup-bug-bash/_partials/gh_cli.md)

**Comment by mdik** [comment]
https://github.com/lewagon/setup/blob/3042f78234553a1b2657df5bf6b393fc16cc54bf/_partials/es/macos_sqlite.md?plain=1#L14
and
https://github.com/lewagon/setup/blob/3042f78234553a1b2657df5bf6b393fc16cc54bf/_partials/es/sqlite.md?plain=1#L14

look a bit too localized, too :sweat_smile:

**Comment by dmilon** [comment]
Hi @lucasgday :wave: Merged :heavy_check_mark: Thank you :pray:
