### ISSUE TITLE
[Mac set up] No radio button for macOS settings->Full Keyboard Access

### ISSUE THREAD

**Issue by malex18** [lewagon/setup#381]
There is no:
radio button `All controls`

<img width="1029" alt="Capture d’écran 2022-04-11 à 17 25 50" src="https://user-images.githubusercontent.com/33787512/162773629-afca90c1-f846-49df-a9e9-4a9fb9b18772.png">

Must have dissiper with the new update ?

<img width="761" alt="Capture d’écran 2022-04-11 à 17 23 51" src="https://user-images.githubusercontent.com/33787512/162773145-51476b22-4a88-407b-9293-20e8ab96d7b8.png">

**Comment by dmilon** [comment]
Hi @malex18 :wave: Thank you for your report :pray: This is going to be fixed withhttps://github.com/lewagon/setup/pull/391
