### ISSUE TITLE
Suggestion: migrating nvm and rbenv to asdf instead

### ISSUE THREAD

**Issue by ashkanyadegari** [lewagon/setup#410]
Hi LW team,

After being loyal to the current setup since 2020, we have tried out to make our lives easier using a version manager tool called [asdf](https://github.com/asdf-vm/asdf). As it supports both Ruby and NodeJS, engineers don't need to have nvm or rbenv installed on their system.

It supports both global and per-project based version management, and is still backward compatible with .ruby-version and .node-versions files.

I think it will make the setup day easier for the students by having less tools to install, and also a cool tool for them to keep using in their post bootcamp workflows.

Just some food for thoughts. I still think nvm and rbenv are relevant, and both really good version managers. Just putting this one out there as a suggestion haha.

**Comment by ajdubovoy** [comment]
Hi! This is a good suggestion. But given that rbenv is much more common in the Ruby world, I think it's best we equip our students' setups to also work naturally in the professional environments they'll find themselves in. For that reason, I'm on the side of closing this for now. Does that sound ok to you, @Eschults ?
