### ISSUE TITLE
Suggestion about `green WSL box`

### ISSUE THREAD

**Issue by SuzukiRyuichiro** [lewagon/setup#417]
In the Windows setup instruction, there is a step to look at WSL green box. However, depending on the theme you are using, it sometimes has totally different colours. I've so far had two tickets just about that. Also, I see on slack that some students have asked the same question before. I think it might be nice if we just remove the color from that sentence. I know it's not the most important thing but just came to my mind as I've had a student who got confused over it.

**Comment by ssaunier** [comment]
I remove the mention of the color, thanks for reporting 🙌
