### ISSUE TITLE
Audit node / webpack / yarn from the setup

### ISSUE THREAD

**Issue by trandthanh** [lewagon/setup#425]
Part of the **More JS in Web Dev Syllabus** (moving towards a full focus on the front-end part of JS and `importmap`), let's remove any mention to the `webpack` bundler and `yarn`. Keeping `node.js` might come in handy, so keeping it might be a safe move.

Tasks:
- [x] Audit mentions of `webpack` to remove them
- [x] Audit mentions of `yarn` to remove them
- [x] Audit mentions of `node.js` to see what is worth keeping

**Comment by Annedj** [comment]
Closing this as there is an open PR removing the mentions of `yarn` 👍
