### ISSUE TITLE
Different postgresql message

### ISSUE THREAD

**Issue by v-natalia** [lewagon/setup#448]
Setup postgresql
https://github.com/lewagon/setup/blob/master/windows.md#postgresql
The guide says:

✔️ If you see a * Starting PostgreSQL 14 database server message, you're good to go 👍 
we should add that the message  **"Starting postgresql (via systemctl): postgresql.service."**  is also fine!

**Comment by ajdubovoy** [comment]
Hi! Already resolved :) thanks for reporting

**Comment by v-natalia** [comment]
Just* I think some students still get the other message

_* Starting PostgreSQL 14 database server_

**Comment by ajdubovoy** [comment]
Interesting. WHy would they receive the old one? Only if they've installed an older version of Postgres?
