### ISSUE TITLE
Ruby VS extension is deprecated

### ISSUE THREAD

**Issue by v-natalia** [lewagon/setup#449]
Section https://github.com/lewagon/setup/blob/master/windows.md#vs-code-extensions

`code --install-extension rebornix.ruby`
Extension Ruby has been deprecated, what is the official suggestion from Le Wagon? Ruby LSP?

https://marketplace.visualstudio.com/items?itemName=Shopify.ruby-lsp 
Please update the guide :)

**Comment by ajdubovoy** [comment]
Duplicate of https://github.com/lewagon/teachers/issues/1780
