### ISSUE TITLE
Windows Setup - USB stick

### ISSUE THREAD

**Issue by andrealmar** [lewagon/setup#46]
On USB Stick part : 

"One of the teacher or TA should give you a bootable USB stick with **Ubuntu 17.10 64 bits.**"

The Link (http://cdimage.ubuntu.com/daily-live/current/artful-desktop-amd64.iso) for the Ubuntu ISO download is NOT working

**Comment by ssaunier** [comment]
We reverted to Ubuntu 16.04 LTS: https://github.com/lewagon/setup/commit/a84709f02ad6c7177519ee5a586f186a0958ac54
