### ISSUE TITLE
Windows/Ubuntu wiki

### ISSUE THREAD

**Issue by krokrob** [lewagon/setup#60]
Teachers are facing recurrent issues about while installing Ubuntu on windows. We need to bring them clearer solutions. A wiki could be good.

**Comment by barangerbenjamin** [comment]
I can only second that
I think @arthur-littm started a "common ubuntu issues" in London.

**Comment by ssaunier** [comment]
I enabled the wiki on this repo if you want to work on it. Thanks 🙏
