### ISSUE TITLE
WSL and access rights

### ISSUE THREAD

**Issue by krokrob** [lewagon/setup#63]
We need to investigate access rights with WSL setup. 
2 related issues have been spotted:
- https://github.com/lewagon/dotfiles/pull/28#issuecomment-402533537 about `syntax-highlighting` zsh plugin fixed by 
```
chmod 0770 ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
```
- `warning: Insecure world writable dir` inside `/home/[USER]` directory fixed by
```
sudo chmod -R go-w /home/[USER]
```

**Comment by mdik** [comment]
```bash
sudo chmod -R go-w /home/[USER]
```
sounds a bit harsh to me.

First, if you need `sudo`, there is probably something else that needs fixing.

Second, `-R` just like that is a bit broad, no?

I'd go

```bash
chmod 0700 $HOME
```

if it is the home directory itself, or

```bash
find $HOME -type d -exec chmod go-w {} \;
```
to limit this on directories (or maybe go explicitly `0700`, `0750`, or `0770`).

Idk, I think it comes down to balancing different gut feelings about what things these commands might break in the long run :joy:

**Comment by mdik** [comment]
Hi,

can we please add the

```
chmod 0770 ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
```

 to the end of the oh-my-zsh section?

I forgot about it, and it was a bit annoying today during setup :-s
