### ISSUE TITLE
$PATH rbenv zsh

### ISSUE THREAD

**Issue by chachine** [lewagon/setup#64]
Setup tutorial(rbenv part)  ask to run :`sudo apt-get install -y build-essential tklib zlib1g-dev libssl-dev libffi-dev libxml2 libxml2-dev libxslt1-dev libreadline-dev
sudo apt-get clean
git clone https://github.com/rbenv/rbenv.git ~/.rbenv
git clone https://github.com/rbenv/ruby-build.git ~/.rbenv/plugins/ruby-build
`
But sometime Zsh dont update the $path to understand 'rbenv' which result in a 'command not found' error.
To manually reasign the $PATH you need to run : 
`$ echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.zshenv

$ echo 'eval "$(rbenv init -)"' >> ~/.zshenv

$ echo 'source $HOME/.zshenv' >> ~/.zshrc

$ exec $SHELL`

**Comment by ssaunier** [comment]
Opening the `~/.zshrc` with a text editor, reading it and making sure it looks like the [recommended `.zshrc`](https://github.com/lewagon/dotfiles/blob/master/zshrc) solves most issues.

Thanks for the comment, closing but leaving for future Google Search reference
