### ISSUE TITLE
Opening graphic interface from WSL to Xming

### ISSUE THREAD

**Issue by barangerbenjamin** [lewagon/setup#65]
Hello,

The setup indicates for Xming part
`echo "export DISPLAY=:0" >> ~/.zshrc`
but it should be
`echo "export DISPLAY=localhost:0.0" >> ~/.zshrc`

**Comment by mdik** [comment]
It works fine with `:0` on all the installations I encountered so far, but it seems the export gets lost during the setup, and needs to be done at a later point during the process.

See https://github.com/lewagon/setup/pull/73

**Comment by barangerbenjamin** [comment]
Just tried with `:0` and it works fine. Closing this issue.
