### ISSUE TITLE
Installing necessary gtk components

### ISSUE THREAD

**Issue by barangerbenjamin** [lewagon/setup#71]
Sublime needs some graphical components from the GTK libraries that apt isn’t smart enough to download automatically. We can install them with this command:

`sudo apt-get install libgtk2.0-0`

Student needs to restart terminal after.

**Comment by mdik** [comment]
https://github.com/lewagon/setup/pull/73#issuecomment-427843687

**Comment by mdik** [comment]
I'd rather use `apt` (without the -get), but yes!

https://github.com/lewagon/setup/pull/73#issuecomment-427846759
