### ISSUE TITLE
PostgreSQL autostart

### ISSUE THREAD

**Issue by mdik** [lewagon/setup#79]
Hi,

with the new Ubuntu `/etc/rc.local` isn't working for autostart purposes anymore.

The simplest way I could find would be

```
sudo echo "`whoami` ALL=NOPASSWD:/etc/init.d/postgresql start" | sudo tee /etc/sudoers.d/postgresql
sudo chmod 440 /etc/sudoers.d/postgresql
echo "sudo /etc/init.d/postgresql start" >> ~/.zshrc
```

Sincerely,

Malte

**Comment by Martin-Alexander** [comment]
Another option is to install PSQL windows-side. You'll have to add the binary folder to the path and add something like `export PG_HOST=localhost` to `.bashrc`/`.zshrc`

**Comment by db0sch** [comment]
@mdik this has been added to the source files.

cf https://github.com/lewagon/setup/blob/master/_partials/wls_postgresql.md

Closing this issue.
