### ISSUE TITLE
Bitlocker Encrypted drive (Dell laptops) breaks dual boot

### ISSUE THREAD

**Issue by barangerbenjamin** [lewagon/setup#91]
It is common practise for Dell to encrypt their drive with Bitlocker.
If you install Ubuntu on dual boot on it (it'll work), you'll have to type the encrypt key every time you want to boot on Windows again (it's 48 characters and there's no copy paste)

So before the setup, for the dell laptop, we'd need to check if the drive is encrypted, and if it is, decrypt following this tutorial:

http://users.isr.ist.utl.pt/~mbayat/hacks/how-to-remove-bitlocker-encryption-in-windows-10/

**Comment by ssaunier** [comment]
@barangerbenjamin Just had this issue today with a student. Can't we just add GUI instructions to `WINDOWS.md`?

```
1. Click Start, click Control Panel, click System and Security, and then click BitLocker Drive Encryption.
2. Look for the drive on which you want BitLocker Drive Encryption turned off, and click Turn Off BitLocker.
3. A message will be displayed, stating that the drive will be decrypted and that decryption may take some time. Click Turn off Bitlocker / Decrypt the drive to continue and turn off BitLocker on the drive.
```

[Source](https://www.manageengine.com/products/os-deployer/help/how-to-disable-bitlocker-encryption.html)

**Comment by barangerbenjamin** [comment]
We can close this issue has we don't do dual boot anymore
