### ISSUE TITLE
Mac OS Mojave gem installation line

### ISSUE THREAD

**Issue by ChristianBell1995** [lewagon/setup#94]
When running the line for installing gems:
```gem install rake bundler rspec rubocop pry pry-byebug hub colored octokit```
I ran into an error due to having OS Mojave - think it was related to this: 
https://stackoverflow.com/questions/54786580/error-while-executing-gem-typeerror-incompatible-marshal-file-format-can, and was fixed by updating the gem sources. 

Thought I would let you know in case this is something that needs updating on the docs or whether it was just for my computer.

**Comment by ssaunier** [comment]
Thanks for reporting! I removed the `.gemrc` we had in default Le Wagon's dotfiles which was a bit dated.
